[package]
name = "peat"
version = "0.0.1"
authors = ["Finn <finn.bcd@gmail.com>"]
license = "CC0-1.0"
edition = "2018"

description = "Peat runtime environment"
keywords = ["scripting", "language"]
repository = "https://github.com/JohnBSmith/peat"
readme = "README.md"

[dependencies]
